

###
PUT http://localhost:5000/editPublication/63e2d5dfe957e218fd11b552 HTTP/1.1
Content-Type: application/json

{   
    "id_Publication":"4",
    "Topic":" Constantes",
    "Category":"Programacion",
    "Detail":"Detalle de las variables",
    "Comment":"Un comentario sobre las variables"
}
###
POST http://localhost:5000/createPublication HTTP/1.1
Content-Type: application/json

{   
    "id_Publication":"4",
    "Topic":"Variables",
    "Category":"Programacion",
    "Detail":"Detalle de las variables",
    "Comment":"Un comentario sobre las variables"
}

